// The binary, not its OpenAPI document, is the compatibility oracle. Keep every
// supported route here even when a method advertised by OpenAPI returns 404.
const tag = "parity-v006";
const document = {
  content: "A compatibility fixture about the harbor kingfisher.",
  customId: "parity-v006-document",
  containerTag: tag,
  metadata: { fixture: "v0.0.6" },
};

export const cases = [
  { name: "v3-documents-create", method: "POST", path: "/v3/documents", body: document },
  { name: "v3-documents-create-invalid", method: "POST", path: "/v3/documents", body: {} },
  { name: "v3-documents-batch", method: "POST", path: "/v3/documents/batch", body: { documents: [document, { ...document, customId: "parity-v006-batch" }] } },
  { name: "v3-documents-batch-invalid", method: "POST", path: "/v3/documents/batch", body: { documents: [{}] } },
  { name: "v3-documents-get", method: "GET", path: "/v3/documents/{documentId}" },
  { name: "v3-documents-get-missing", method: "GET", path: "/v3/documents/missing-parity-v006" },
  { name: "v3-documents-update", method: "PATCH", path: "/v3/documents/{documentId}", body: { content: "An updated harbor kingfisher fixture." } },
  { name: "v3-documents-update-invalid", method: "PATCH", path: "/v3/documents/{documentId}", body: {} },
  { name: "v3-documents-list", method: "POST", path: "/v3/documents/list", body: { containerTag: tag, limit: 10 } },
  { name: "v3-documents-list-invalid", method: "POST", path: "/v3/documents/list", body: { limit: -1 } },
  { name: "v3-documents-processing", method: "GET", path: "/v3/documents/processing" },
  { name: "v3-documents-chunks", method: "GET", path: "/v3/documents/{documentId}/chunks" },
  { name: "v3-documents-file-url", method: "GET", path: "/v3/documents/{documentId}/file-url" },
  { name: "v3-documents-file-invalid", method: "POST", path: "/v3/documents/file", body: {} },
  { name: "v3-documents-bulk-delete-invalid", method: "DELETE", path: "/v3/documents/bulk", body: {} },
  { name: "v3-search", method: "POST", path: "/v3/search", body: { q: "kingfisher", containerTag: tag } },
  { name: "v3-search-invalid", method: "POST", path: "/v3/search", body: {} },
  { name: "v3-settings-get", method: "GET", path: "/v3/settings" },
  { name: "v3-settings-update-invalid", method: "PATCH", path: "/v3/settings", body: {} },
  { name: "v3-settings-reset", method: "POST", path: "/v3/settings/reset", body: {} },
  { name: "v3-settings-suggest-buckets-invalid", method: "POST", path: "/v3/settings/suggest-buckets", body: {} },
  { name: "v3-container-tag-get-missing", method: "GET", path: "/v3/container-tags/missing-parity-v006" },
  { name: "v3-container-tag-update-invalid", method: "PATCH", path: "/v3/container-tags/{tag}", body: {} },
  { name: "v3-container-tag-delete-missing", method: "DELETE", path: "/v3/container-tags/missing-parity-v006" },
  { name: "v3-container-tag-merge-invalid", method: "POST", path: "/v3/container-tags/merge", body: {} },
  { name: "v3-container-tag-merge-get-missing", method: "GET", path: "/v3/container-tags/merge/missing-parity-v006" },
  { name: "v4-memories-create-invalid", method: "POST", path: "/v4/memories", body: {} },
  { name: "v4-memories-update-missing", method: "PATCH", path: "/v4/memories", body: { id: "missing-parity-v006" } },
  { name: "v4-memories-delete-missing", method: "DELETE", path: "/v4/memories", body: { id: "missing-parity-v006" } },
  { name: "v4-memories-list", method: "POST", path: "/v4/memories/list", body: { containerTag: tag, limit: 10 } },
  { name: "v4-memories-list-invalid", method: "POST", path: "/v4/memories/list", body: {} },
  { name: "v4-memories-forget-matching-invalid", method: "POST", path: "/v4/memories/forget-matching", body: {} },
  { name: "v4-profile", method: "POST", path: "/v4/profile", body: { containerTag: tag } },
  { name: "v4-profile-invalid", method: "POST", path: "/v4/profile", body: {} },
  { name: "v4-profile-buckets", method: "POST", path: "/v4/profile/buckets", body: { containerTag: tag } },
  { name: "v4-profile-buckets-invalid", method: "POST", path: "/v4/profile/buckets", body: {} },
  { name: "v4-search", method: "POST", path: "/v4/search", body: { q: "kingfisher", containerTag: tag } },
  { name: "v4-search-invalid", method: "POST", path: "/v4/search", body: {} },
  { name: "v4-conversations-invalid", method: "POST", path: "/v4/conversations", body: {} },
  // Deletions run last because the primary fixture document is needed above.
  { name: "v3-documents-bulk-delete", method: "DELETE", path: "/v3/documents/bulk", body: { ids: ["{documentId}"] } },
  { name: "v3-documents-delete-missing", method: "DELETE", path: "/v3/documents/missing-parity-v006" },
];
