[package]
name = "server"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
axum.workspace = true
http.workspace = true
serde_json.workspace = true
serde.workspace = true
sha2.workspace = true
storage = { path = "../storage" }
subtle.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tower.workspace = true

[lints]
workspace = true
